use DBexp;
Go
/*«Â¿Ì±Ì*/
ALTER TABLE B_L DROP constraint C2;
ALTER TABLE B_L DROP constraint C3;
DROP TABLE IF EXISTS B_L;

Go
ALTER TABLE FOLLOW DROP constraint C4;
ALTER TABLE FOLLOW DROP constraint C5;
DROP TABLE IF EXISTS FOLLOW;

Go
ALTER TABLE FRIENDS DROP constraint C6;
ALTER TABLE FRIENDS DROP constraint C7;
DROP TABLE IF EXISTS FRIENDS;

Go
ALTER TABLE SUB DROP constraint C8;
ALTER TABLE SUB DROP constraint C9;
DROP TABLE IF EXISTS SUB;

Go
ALTER TABLE THUMB DROP constraint C10;
ALTER TABLE THUMB DROP constraint C11;
DROP TABLE IF EXISTS THUMB;

Go
ALTER TABLE TOPDAY DROP constraint C12;
DROP TABLE IF EXISTS TOPDAY;

Go
DROP TABLE IF EXISTS LABEL;

Go
--ALTER TABLE MBLOG DROP constraint C1;
DROP TABLE IF EXISTS MBLOG;

Go
DROP TABLE IF EXISTS USERS;

DROP TABLE IF EXISTS FANS_3;
DROP TABLE IF EXISTS TOP_THUMB;
DROP TABLE IF EXISTS test;



