use DBexp
go

SET TRAN ISOLATION LEVEL READ UNCOMMITTED
SET TRAN ISOLATION LEVEL READ COMMITTED
SET TRAN ISOLATION LEVEL REPEATABLE READ
SET TRAN ISOLATION LEVEL SERIALIZABLE

SET TRAN ISOLATION LEVEL SNAPSHOT
select * from test where ID=2;
WAITFOR DELAY '00:00:10'
select * from test where ID=2;

