.386  
STACK   SEGMENT     USE16   STACK
        DB 200  DUP(0)
STACK   ENDS
CODE    SEGMENT     USE16
        ASSUME  CS:CODE,  SS:STACK
START: 
		XOR AX,AX
		MOV DS,0
		MOV AH,35H	
		MOV AL,1H
		INT 21H
		MOV AH,35H	
		MOV AL,10H
		INT 21H
		MOV AH,4CH 
		INT 21H 
CODE ENDS
END START 