.386
DATA   SEGMENT USE16 
DATA   ENDS
CODE   SEGMENT USE16 
       ASSUME CS:CODE,SS:STACK
		
START:  XOR AX,AX
        MOV DS,AX
  
		CLI
        MOV BYTE PTR DS:[16H*4],224
		MOV BYTE PTR DS:[16H*4+1],01H
		MOV BYTE PTR DS:[16H*4+2],00H
		MOV BYTE PTR DS:[16H*4+3],241
        STI

        MOV DX,OFFSET START+15
	    SHR DX,4
        ADD DX,10H
	   
        MOV AL,0
        MOV AH,31H
        INT 21H
CODE   ENDS
STACK  SEGMENT USE16 STACK
       DB 200 DUP(0)
STACK  ENDS
       END START
